name: Docker_Image_CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  GITHUBREADPACKAGE: ${{ secrets.GITHUB_READ_PACKAGE }}
  USERNAME: MohammadJS2642

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: copy nuget
      run: mv nuget_action.config nuget.config
    - name: Build the Docker image
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: docker build . --file ./WebApplication2/Dockerfile --tag my-image-name:$(date +%s)
