name: Docker_Image_CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    #- name: Add Github Package source
    #  working-directory: ./WebApplication2
    #  run: |
    #      dotnet nuget add source --username MohammadJS2642  --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/MohammadJS2642/index.json"
    - name: Build the Docker image
      with: 
        context: ./WebApplication2
        working-directory: ./WebApplication2
      run: docker build ./ --file Dockerfile --tag my-image-name:$(date +%s)
      #run: ls
