name: Docker_Image_CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  USERNAME: MohammadJS2642
  PASS: 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
  URL: https://nuget.pkg.github.com/MohammadJS2642/index.json

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    #- name: Add Dependencies
    #  working-directory: ./WebApplication2
    #  run: dotnet nuget add source --username ${{ env.USERNAME }} --store-password-in-clear-text --configfile "nuget.config" -p ${{ env.PASS }}  --name github ${{ env.URL }}

    #- name: Add Packages
    #  working-directory: ./WebApplication2
    #  run: dotnet add "WebApplication2.csproj" package MyPackageDevelopmentPackage --version 0.1.30

    - name: Build the Docker image
      working-directory: WebApplication1_Solution
      run: docker build ./ --file Dockerfile --tag my-image-name:$(date +%s)
