name: Docker_Image_CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  USERNAME: MohammadJS2642
  #PASS: ${{ secrets.GITHUB_TOKEN }}
  PASS: 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
  URL: https://nuget.pkg.github.com/MohammadJS2642/index.json
  GITHUBTOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    #- name: copy to nuget
    #  run: mkdir -p ~/.nuget/NuGet && cp ./nuget.config ~/.nuget/NuGet/NuGet.config
    
    - name: enable nuget sources
      run: dotnet nuget list source

    - name: Add Nuget.Config file to cache
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Add nuget.config to path
      run: cp ./nuget.config ~/.nuget/NuGet/NuGet.Config

    #- name: Add nuget.config
    #  run: dotnet nuget add source --username MohammadJS2642 -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/MohammadJS2642/index.json"

    #- name: Add Packages
    #  working-directory: ./WebApplication2
    #  run: dotnet add "WebApplication2.csproj" package MyPackageDevelopmentPackage --version 0.1.30

    - name: Build the Docker image
      working-directory: ./
      run: docker build ./WebApplication2 --file ./WebApplication2/Dockerfile --tag my-image-name:$(date +%s)
