name: Docker_Image_CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  USERNAME: MohammadJS2642
  PASS: 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
  URL: https://nuget.pkg.github.com/MohammadJS2642/index.json

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    #- name: copy to nuget
    #  run: mkdir -p ~/.nuget/NuGet && cp ./nuget.config ~/.nuget/NuGet/NuGet.config
    
    - name: enable nuget sources
      run: dotnet nuget list source

    #- name: Add Packages
    #  working-directory: ./WebApplication2
    #  run: dotnet add "WebApplication2.csproj" package MyPackageDevelopmentPackage --version 0.1.30

    - name: Build the Docker image
      with:
       secrets: "github_token=${{ secrets.GITHUB_TOKEN }}"
      working-directory: ./
      run: docker build ./WebApplication2 --file ./WebApplication2/Dockerfile --tag my-image-name:$(date +%s)
      #run: docker build ./WebApplication2 --file ./WebApplication2/Dockerfile --tag my-image-name:$(date +%s)
