name: Docker_Image_CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# added to read from github repository
#environment: someName
env:
  GITHUBREADPACKAGE: ${{ secrets.GITHUB_READ_PACKAGE }}
  USERNAME: MohammadJS2642
#  URL: https://nuget.pkg.github.com/MohammadJS2642/index.json
#  GITHUBTOKEN: ${{ secrets.GITHUB_READ_PACKAGE }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    #- uses: actions/setup-dotnet@v3
    #  with:
    #     global-json-file:  ./global.json
    #     source-url: $URL
    #  env:
    #    NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    #- name: Add Nuget.Config file to cache
    #  uses: actions/cache@v3
    #  with:
    #    path: ~/.nuget/packages
    #    key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
    #    restore-keys: |
    #      ${{ runner.os }}-nuget-
    #- name: Add nuget.config to path
    #  run: cp ./nuget.config ~/.nuget/NuGet/NuGet.Config
    #- name: Add NugetConfig
    #  run: dotnet new nugetconfig --force
    - name: Add nuget.config
      run: dotnet nuget add source --username MohammadJS2642 --store-password-in-clear-text --name github "https://nuget.pkg.github.com/MohammadJS2642/index.json"
    - name: Build the Docker image
      working-directory: ./
      run: docker build . --file ./WebApplication2\Dockerfile --tag my-image-name:$(date +%s)
